require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'SanthiyaPothi' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enable Flipper
  # Note that if you have use_frameworks! enabled, Flipper will not work and you should disable these next few lines.
  flipper_versions = {
    'Flipper' => '0.125.0',
    'Flipper-Folly' => '2.6.10',
    'Flipper-RSocket' => '1.4.3'
  }

  use_flipper!({
    'Flipper' => flipper_versions['Flipper'],
    'Flipper-Folly' => flipper_versions['Flipper-Folly'],
    'Flipper-RSocket' => flipper_versions['Flipper-RSocket']
  })

  target 'SanthiyaPothiTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end
